version: '3.8'

services:
  # Frontend application
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:3001/api/v1
    depends_on:
      - backend

  # Backend API server
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGO_URI=mongodb://mongodb:27017/blockchain-intel
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=blockchain-intel-password
      - ELASTIC_URI=http://elasticsearch:9200
      - ETH_PROVIDER_URL=https://mainnet.infura.io/v3/your-infura-key
    depends_on:
      - mongodb
      - neo4j
      - elasticsearch

  # MongoDB for user data, configurations, and historical aggregations
  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=blockchain-intel

  # Neo4j for graph data (entity relationships, transaction flows)
  neo4j:
    image: neo4j:4.4
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/blockchain-intel-password
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2G

  # Elasticsearch for fast address and transaction searches
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx1g"
      - xpack.security.enabled=false

  # Kibana for visualization and Elasticsearch management
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

volumes:
  mongodb_data:
  neo4j_data:
  neo4j_logs:
  elasticsearch_data: